import type { SkillReference } from "./types";

/** 来源链接核对于 2026-09-28；页面只展示名称。 */
export const guideResources = {
  "music": {"name":"music","href":"https://github.com/elevenlabs/skills/blob/main/music/SKILL.md"},
  "tts": {"name":"text-to-speech","href":"https://github.com/elevenlabs/skills/blob/main/text-to-speech/SKILL.md"},
  "stt": {"name":"speech-to-text","href":"https://github.com/elevenlabs/skills/blob/main/speech-to-text/SKILL.md"},
  "dubbing": {"name":"dubbing","href":"https://github.com/elevenlabs/skills/blob/main/dubbing/SKILL.md"},
  "sfx": {"name":"sound-effects","href":"https://github.com/elevenlabs/skills/blob/main/sound-effects/SKILL.md"},
  "isolation": {"name":"voice-isolator","href":"https://github.com/elevenlabs/skills/blob/main/voice-isolator/SKILL.md"},
  "changer": {"name":"voice-changer","href":"https://github.com/elevenlabs/skills/blob/main/voice-changer/SKILL.md"},
  "voiceAgent": {"name":"agents","href":"https://github.com/elevenlabs/skills/blob/main/agents/SKILL.md"},
  "speechEngine": {"name":"speech-engine","href":"https://github.com/elevenlabs/skills/blob/main/speech-engine/SKILL.md"},
  "speech": {"name":"speech","href":"https://github.com/openai/skills/blob/main/skills/.curated/speech/SKILL.md"},
  "transcribe": {"name":"transcribe","href":"https://github.com/openai/skills/blob/main/skills/.curated/transcribe/SKILL.md"},
  "creator": {"name":"skill-creator","href":"https://github.com/anthropics/skills/blob/main/skills/skill-creator/SKILL.md"},
  "mcp": {"name":"mcp-builder","href":"https://github.com/anthropics/skills/blob/main/skills/mcp-builder/SKILL.md"},
  "spreadsheet": {"name":"xlsx","href":"https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md"},
  "browser": {"name":"browser-use","href":"https://github.com/browser-use/browser-use/blob/main/skills/browser-use/SKILL.md"},
  "n8n": {"name":"n8n-workflow-patterns","href":"https://github.com/czlonkowski/n8n-skills/blob/main/skills/n8n-workflow-patterns/SKILL.md"},
  "n8nErrors": {"name":"n8n-error-handling","href":"https://github.com/czlonkowski/n8n-skills/blob/main/skills/n8n-error-handling/SKILL.md"},
  "plans": {"name":"writing-plans","href":"https://github.com/obra/superpowers/blob/main/skills/writing-plans/SKILL.md"},
  "debug": {"name":"systematic-debugging","href":"https://github.com/obra/superpowers/blob/main/skills/systematic-debugging/SKILL.md"},
  "tdd": {"name":"test-driven-development","href":"https://github.com/obra/superpowers/blob/main/skills/test-driven-development/SKILL.md"},
  "frontend": {"name":"frontend-design","href":"https://github.com/anthropics/skills/blob/main/skills/frontend-design/SKILL.md"},
  "webTesting": {"name":"webapp-testing","href":"https://github.com/anthropics/skills/blob/main/skills/webapp-testing/SKILL.md"},
  "react": {"name":"react-best-practices","href":"https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/SKILL.md"},
  "composition": {"name":"composition-patterns","href":"https://github.com/vercel-labs/agent-skills/blob/main/skills/composition-patterns/SKILL.md"},
  "uiReview": {"name":"web-design-guidelines","href":"https://github.com/vercel-labs/agent-skills/blob/main/skills/web-design-guidelines/SKILL.md"},
  "postgres": {"name":"supabase-postgres-best-practices","href":"https://github.com/supabase/agent-skills/blob/main/skills/supabase-postgres-best-practices/SKILL.md"},
  "security": {"name":"security-best-practices","href":"https://github.com/openai/skills/blob/main/skills/.curated/security-best-practices/SKILL.md"},
  "stitchPrompt": {"name":"enhance-prompt","href":"https://github.com/google-labs-code/stitch-skills/blob/main/plugins/stitch-utilities/skills/enhance-prompt/SKILL.md"},
  "stitchDesign": {"name":"stitch::generate-design","href":"https://github.com/google-labs-code/stitch-skills/blob/main/plugins/stitch-design/skills/generate-design/SKILL.md"},
  "designMd": {"name":"design-md","href":"https://github.com/google-labs-code/stitch-skills/blob/main/plugins/stitch-utilities/skills/design-md/SKILL.md"},
  "stitchReact": {"name":"stitch::react-components","href":"https://github.com/google-labs-code/stitch-skills/blob/main/plugins/stitch-build/skills/react-components/SKILL.md"},
  "figma": {"name":"figma-implement-design","href":"https://github.com/openai/skills/blob/main/skills/.curated/figma-implement-design/SKILL.md"},
  "figmaRules": {"name":"figma-create-design-system-rules","href":"https://github.com/openai/skills/blob/main/skills/.curated/figma-create-design-system-rules/SKILL.md"},
  "cf": {"name":"cloudflare","href":"https://github.com/cloudflare/skills/blob/main/skills/cloudflare/SKILL.md"},
  "workers": {"name":"workers-best-practices","href":"https://github.com/cloudflare/skills/blob/main/skills/workers-best-practices/SKILL.md"},
  "durable": {"name":"durable-objects","href":"https://github.com/cloudflare/skills/blob/main/skills/durable-objects/SKILL.md"},
  "wrangler": {"name":"wrangler","href":"https://github.com/cloudflare/skills/blob/main/skills/wrangler/SKILL.md"},
  "cfDeploy": {"name":"cloudflare-deploy","href":"https://github.com/openai/skills/blob/main/skills/.curated/cloudflare-deploy/SKILL.md"},
  "vercelDeploy": {"name":"vercel-deploy","href":"https://github.com/openai/skills/blob/main/skills/.curated/vercel-deploy/SKILL.md"},
  "ci": {"name":"gh-fix-ci","href":"https://github.com/openai/skills/blob/main/skills/.curated/gh-fix-ci/SKILL.md"},
  "sentry": {"name":"sentry","href":"https://github.com/openai/skills/blob/main/skills/.curated/sentry/SKILL.md"},
  "perf": {"name":"web-perf","href":"https://github.com/cloudflare/skills/blob/main/skills/web-perf/SKILL.md"},
} as const satisfies Record<string, SkillReference>;

export type GuideResourceId = keyof typeof guideResources;
